Repository ln-vortex/ln-vortex, pull requests merged in 2022-09, with the labels that each got.

#216 Add transaction types
  app/config/src/main/scala/com/lnvortex/config/VortexPicklers.scala
  core/src/main/scala/com/lnvortex/core/RoundDetails.scala
  core/src/main/scala/com/lnvortex/core/api/TransactionType.scala
Labels: enhancement

#219 Remove on-chain tx type for WITNESS_V0_SCRIPTHASH output types
  core/src/main/scala/com/lnvortex/core/api/TransactionType.scala
Labels: bug

#218 Correctly verify fees & script types as client
  client-test/src/test/scala/com/lnvortex/client/VortexClientTest.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/VortexClientException.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: client

#220 Basic docker deployments
  .github/workflows/docker.yml
  app/rpc-server/rpc-server.sbt
  app/rpc-server/src/main/universal/docker-application.conf
  app/rpc-server/src/main/universal/logback.xml
  build.sbt
  coordinator/rpc-server/coordinator-rpc-server.sbt
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/ServerArgParser.scala
  coordinator/rpc-server/src/main/universal/docker-application.conf
  project/CommonSettings.scala
  project/plugins.sbt
Labels: build

#221 Fix project names
  .github/workflows/docker.yml
Labels: bug

#227 Update sbt-native-packager
  project/plugins.sbt
Labels: dependencies

#228 Use better outpoint read/writes
  app/config/src/main/scala/com/lnvortex/config/VortexPicklers.scala
Labels: client

#232 Fixes for docker snapshots
  app/rpc-server/rpc-server.sbt
  build.sbt
  coordinator/rpc-server/coordinator-rpc-server.sbt
  inThisBuild.sbt
  project/CommonSettings.scala
Labels: build

#234 Only update isLatest when isRelease
  project/CommonSettings.scala
Labels: build

#235 Fix logback timezone config
  app/rpc-server/src/main/universal/logback.xml
  core/src/main/resources/logback.xml
Labels: build

#236 Set proper coordinator seed file name
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
  server/src/main/scala/com/lnvortex/server/coordinator/CoordinatorKeyManager.scala
Labels: bug, coordinator

#238 Add more docker config options
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LightningImplementation.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexAppConfig.scala
  app/rpc-server/src/universal/docker-application.conf
  coordinator/config/src/main/scala/com/lnvortex/coordinator/config/LnVortexRpcServerConfig.scala
  coordinator/rpc-server/src/universal/docker-application.conf
Labels: build

#242 Update akka deps
  project/Deps.scala
Labels: dependencies

#244 Simplify logging deps
  project/Deps.scala
Labels: dependencies

#245 Add bitcoind config options to coordinator docker config
  coordinator/rpc-server/src/universal/docker-application.conf
Labels: build

#246 Skip creating torKeys folder if just tor proxy is enabled
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
Labels: bug

#247 Add coordinator rpc credentials to docker config
  coordinator/rpc-server/src/universal/docker-application.conf
Labels: build

#254 Update README to correct lnd version
  README.md
Labels: documentation

#252 Print build tags on error
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: lnd

#259 Change project name to ln-vortex
  bitcoind-test/bitcoind-test.sbt
  build.sbt
  client-server-test/client-server-test.sbt
  client-test/client-test.sbt
  clightning-test/clightning-test.sbt
  develop/develop.sbt
  lnd-test/lnd-test.sbt
  project/Projects.scala
  server-test/server-test.sbt
Labels: build

#260 Better shutdown handling
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/Daemon.scala
  server/src/main/scala/com/lnvortex/server/networking/VortexHttpServer.scala
Labels: coordinator

#261 Change default ports based on network
  app/cli/src/main/scala/com/lnvortex/cli/CliReaders.scala
  app/cli/src/main/scala/com/lnvortex/cli/ConsoleCli.scala
  app/config/src/main/scala/com/lnvortex/config/LnVortexRpcServerConfig.scala
  app/rpc-server/rpc-server.sbt
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexAppConfig.scala
  coordinator/cli/src/main/scala/com/lnvortex/coordinator/cli/CliReaders.scala
  coordinator/cli/src/main/scala/com/lnvortex/coordinator/cli/ConsoleCli.scala
  coordinator/config/src/main/scala/com/lnvortex/coordinator/config/LnVortexRpcServerConfig.scala
  coordinator/rpc-server/coordinator-rpc-server.sbt
  core/src/main/scala/com/lnvortex/core/VortexUtils.scala
  project/Deps.scala
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
  server/src/main/scala/com/lnvortex/server/networking/VortexHttpServer.scala
Labels: client, coordinator

#262 Update bitcoin-s
  project/Deps.scala
Labels: dependencies, lnd

#263 Unify CI into single workflow
  .github/workflows/client_server_test.yml
  .github/workflows/compile.yml
  .github/workflows/main.yml
  .github/workflows/postgres_test.yml
  .github/workflows/scala-steward.yml
  .github/workflows/wallet_test.yml
Labels: CI

#265 Make peer node id easier to copy from terminal
  develop/src/main/scala/com/lnvortex/develop/CreateLocalDevEnvironment.scala
Labels: developer enviroment

#266 Set tor variables for docker-compose
  coordinator/rpc-server/src/universal/docker-application.conf
  docker-compose.yml
Labels: build

#268 Small improvements to coordinator
  coordinator/rpc-server/src/universal/docker-application.conf
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
Labels: coordinator

#271 Retain ordering of coordinators
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexRoutes.scala
  client/src/main/scala/com/lnvortex/client/VortexClientManager.scala
  client/src/main/scala/com/lnvortex/client/config/VortexAppConfig.scala
Labels: client

#272 Use correct default port when parsing configured coordinator address
  client/src/main/scala/com/lnvortex/client/config/VortexAppConfig.scala
  core/src/main/resources/reference.conf
Labels: client

#273 Add tor.provided=true to default conf
  core/src/main/resources/reference.conf
Labels: client

#274 Fix default listen address
  core/src/main/resources/reference.conf
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
Labels: coordinator

#275 Set default port correctly for broadcasted coordinators
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
Labels: coordinator

#277 Allow configuring tor targets for coordinator
  coordinator/rpc-server/src/universal/docker-application.conf
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
  server/src/main/scala/com/lnvortex/server/networking/VortexHttpServer.scala
Labels: coordinator

#279 Update bitcoin-s
  project/Deps.scala
Labels: dependencies

#282 Update testnet coordinators to new address
  client-server-test/src/test/scala/com/lnvortex/server/ClientHttpTest.scala
  core/src/main/resources/reference.conf
Labels: client

#284 Download proper lnd mac m1 binaries
  build.sbt
Labels: lnd

#285 Docs: update cancelcoins params
  docs/client-rpc.md
Labels: documentation

#286 Small renames
  app/rpc-server/src/main/scala/com/lnvortex/rpc/Daemon.scala
  build.sbt
  client/src/main/scala/com/lnvortex/client/config/VortexAppConfig.scala
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
Labels: refactor

#287 Add taproot converter coordinator
  client/src/main/scala/com/lnvortex/client/networking/VortexHttpClient.scala
  core/src/main/resources/reference.conf
Labels: client

#289 Add test for multiple cancelations
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairNetworkingTest.scala
Labels: tests

#290 Treat empty string as none for peerAddrOpt
  app/rpc-server/src/main/scala/com/lnvortex/rpc/ServerJsonModels.scala
Labels: client

#293 Allow remixes from other coordinators
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
  server/src/main/scala/com/lnvortex/server/models/RoundDAO.scala
Labels: coordinator

#294 Add debug logs for VortexClient
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/networking/VortexHttpClient.scala
Labels: client

#295 Make vortexWallet private
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexRoutes.scala
  client/src/main/scala/com/lnvortex/client/VortexClientManager.scala
Labels: refactor, client

#296 Unreserve inputs on cancelation of registration
  bitcoind/src/main/scala/com/lnvortex/bitcoind/BitcoindVortexWallet.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningVortexWallet.scala
  core/src/main/scala/com/lnvortex/core/api/VortexWalletApi.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: client

#298 Add ability to auto-requeue for rounds
  app/config/src/main/scala/com/lnvortex/config/VortexPicklers.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/Daemon.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/ServerJsonModels.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/ServerRoute.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/VortexClientRpcRoutes.scala
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairTest.scala
  client-server-test/src/test/scala/com/lnvortex/server/OnChainTest.scala
  client-server-test/src/test/scala/com/lnvortex/server/RemixNetworkingTest.scala
  client-server-test/src/test/scala/com/lnvortex/server/RemixTest.scala
  client-test/src/test/scala/com/lnvortex/client/VortexClientTest.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/db/UTXODAO.scala
  core-test/src/test/scala/com/lnvortex/core/RoundDetailsTest.scala
  core/src/main/scala/com/lnvortex/core/RoundDetails.scala
  develop/src/main/scala/com/lnvortex/develop/CreateLocalDevEnvironment.scala
  project/Deps.scala
  testkit/src/main/scala/com/lnvortex/testkit/ClientServerPairFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/DualClientFixture.scala
Labels: client

#300 Add requeue docs
  docs/client-rpc.md
Labels: documentation

#301 Drop the 'ln'
  README.md
  docs/client-rpc.md
Labels: documentation

#303 Add code coverage checks
  .github/workflows/main.yml
  README.md
  project/plugins.sbt
Labels: tests

#304 Fix link in readme
  README.md
Labels: documentation

#305 Fix readme badge
  README.md
Labels: documentation

#306 Rework CI
  .github/workflows/main.yml
  build.sbt
  project/Deps.scala
Labels: CI

#307 Redo CI into single test
  .github/workflows/main.yml
Labels: CI

#308 Increase bitcoind code coverage
  bitcoind-test/src/test/scala/com/lnvortex/bitcoind/BitcoindVortexWalletTest.scala
Labels: bitcoind, tests

#309 Increase core test coverage
  core-test/src/test/scala/com/lnvortex/core/VortexUtilsTest.scala
  core/src/main/scala/com/lnvortex/core/InputReference.scala
  core/src/main/scala/com/lnvortex/core/NodeUri.scala
  core/src/main/scala/com/lnvortex/core/RoundStatus.scala
  develop/develop.sbt
  lnd/src/main/scala/com/lnvortex/lnd/LndChannelOpener.scala
Labels: tests

#312 Fix bitcoind test
  bitcoind-test/src/test/scala/com/lnvortex/bitcoind/BitcoindVortexWalletTest.scala
Labels: bug, tests

#313 Add more coordinator tests
  server-test/src/test/scala/com/lnvortex/server/coordinator/VortexCoordinatorTest.scala
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
  server/src/main/scala/com/lnvortex/server/models/AliceDAO.scala
  server/src/main/scala/com/lnvortex/server/models/AliceDb.scala
  server/src/main/scala/com/lnvortex/server/models/RegisteredInputDAO.scala
Labels: coordinator, tests

#310 Add test for opening channel when no peer is connected
  .github/workflows/main.yml
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairNetworkingTest.scala
  client/src/main/scala/com/lnvortex/client/db/UTXODAO.scala
  clightning-test/src/test/scala/com/lnvortex/clightning/CLightningVortexWalletTest.scala
  lnd-test/src/test/scala/com/lnvortex/lnd/LndVortexWalletTest.scala
Labels: tests

#311 Add tests for getRoundParams
  client-server-test/src/test/scala/com/lnvortex/server/ClientHttpTest.scala
  client/src/main/scala/com/lnvortex/client/networking/VortexHttpClient.scala
  testkit/src/main/scala/com/lnvortex/testkit/HttpTestFixture.scala
Labels: tests

#314 Gen coverage report on merge
  .github/workflows/coverage_report.yml
Labels: CI

#315 Print stack trace on failed requeues
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
Labels: documentation

#316 Error on bad download
  build.sbt
Labels: build

#317 Turn off coverage reporting on ScriptType matches
  bitcoind/src/main/scala/com/lnvortex/bitcoind/BitcoindVortexWallet.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningVortexWallet.scala
  core/src/main/scala/com/lnvortex/core/FeeCalculator.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
Labels: tests

#318 Update bitcoin-s
  lnd/src/main/scala/com/lnvortex/lnd/LndChannelOpener.scala
  project/Deps.scala
Labels: dependencies

#319 Exclude RPC servers from code coverage
  build.sbt
Labels: tests

#322 Remove unneeded peer address param in initPSBTChannelOpen
  bitcoind-test/src/test/scala/com/lnvortex/bitcoind/BitcoindVortexWalletTest.scala
  bitcoind/src/main/scala/com/lnvortex/bitcoind/BitcoindVortexWallet.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningChannelOpener.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningVortexWallet.scala
  core/src/main/scala/com/lnvortex/core/api/VortexWalletApi.scala
  lnd-test/src/test/scala/com/lnvortex/lnd/LndChannelOpenerTest.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndChannelOpener.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: refactor

#321 Get nonce message from websocket through a promise
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairNetworkingTest.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/networking/VortexHttpClient.scala
  testkit/src/main/scala/com/lnvortex/testkit/ClientServerPairFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/ClientServerTestUtils.scala
Labels: refactor, client

#320 Add end-to-end tests for CLN
  .github/workflows/main.yml
  client-server-test/src/test/scala/com/lnvortex/server/CLNNetworkingTest.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningVortexWallet.scala
  testkit/src/main/scala/com/lnvortex/testkit/CLNClientServerPairFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/CLNTestUtils.scala
Labels: CLN, tests

#324 Add a couple more lightning vortex wallet tests
  clightning-test/src/test/scala/com/lnvortex/clightning/CLightningVortexWalletTest.scala
  lnd-test/src/test/scala/com/lnvortex/lnd/LndVortexWalletTest.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: tests

#323 Complete nonce message promise after it is stored
  client-server-test/src/test/scala/com/lnvortex/server/RemixTest.scala
  client/src/main/scala/com/lnvortex/client/networking/VortexHttpClient.scala
Labels: bug, client

#325 Add a bunch of unit tests
  client-server-test/src/test/scala/com/lnvortex/server/CLNNetworkingTest.scala
  client-test/src/test/scala/com/lnvortex/client/VortexClientManagerTest.scala
  client-test/src/test/scala/com/lnvortex/client/VortexClientTest.scala
  client-test/src/test/scala/com/lnvortex/client/VortexClientUnitTest.scala
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/VortexClientManager.scala
  clightning-test/src/test/scala/com/lnvortex/clightning/CLightningVortexWalletTest.scala
  core/src/main/resources/reference.conf
  lnd-test/src/test/scala/com/lnvortex/lnd/LndVortexWalletTest.scala
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
  testkit/src/main/scala/com/lnvortex/testkit/CLNClientServerPairFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/LnVortexTestUtils.scala
  testkit/src/main/scala/com/lnvortex/testkit/VortexClientManagerFixture.scala
Labels: tests

#327 Add isVortex to TransactionDetails
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairTest.scala
  client-server-test/src/test/scala/com/lnvortex/server/OnChainTest.scala
  client/src/main/resources/postgresql/vortex/migration/V1__baseline.sql
  client/src/main/resources/sqlite/vortex/migration/V1__baseline.sql
  client/src/main/scala/com/lnvortex/client/VortexClient.scala
  client/src/main/scala/com/lnvortex/client/VortexClientManager.scala
  client/src/main/scala/com/lnvortex/client/db/UTXODAO.scala
  client/src/main/scala/com/lnvortex/client/db/UTXODb.scala
  clightning/src/main/scala/com/lnvortex/clightning/CLightningVortexWallet.scala
  core/src/main/scala/com/lnvortex/core/RoundDetails.scala
  core/src/main/scala/com/lnvortex/core/api/TransactionDetails.scala
  docs/client-rpc.md
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: client

#329 Add logo header to ReadMe
  README.md
  docs/assets/vortex-dark-mode.svg
  docs/assets/vortex-light-mode.svg
Labels: documentation

#330 Implemenent listTransactions for bitcoind
  bitcoind-test/src/test/scala/com/lnvortex/bitcoind/BitcoindVortexWalletTest.scala
  bitcoind/src/main/scala/com/lnvortex/bitcoind/BitcoindVortexWallet.scala
  project/Deps.scala
Labels: bitcoind

#331 Add debug logs for coordinator
  server-test/src/test/scala/com/lnvortex/server/coordinator/VortexCoordinatorTest.scala
  server/src/main/scala/com/lnvortex/server/coordinator/CoordinatorKeyManager.scala
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
  server/src/main/scala/com/lnvortex/server/networking/CoordinatorRoutes.scala
  testkit/src/main/scala/com/lnvortex/testkit/ClientServerTestUtils.scala
Labels: coordinator

#332 Add socks5 proxy to docker config
  app/rpc-server/src/universal/docker-application.conf
Labels: build, client

#333 Fix typo in docker configs
  app/rpc-server/src/universal/docker-application.conf
  coordinator/rpc-server/src/universal/docker-application.conf
Labels: build

#335 Tag docker images as master
  .github/workflows/docker.yml
  project/CommonSettings.scala
Labels: build, CI

#334 Working docker-compose file!
  docker-compose.yml
Labels: build

#336 A little more test coverage
  bitcoind-test/src/test/scala/com/lnvortex/bitcoind/BitcoindVortexWalletTest.scala
  core-test/src/test/scala/com/lnvortex/core/ClientStatusTest.scala
  core-test/src/test/scala/com/lnvortex/core/RoundDetailsTest.scala
  core-test/src/test/scala/com/lnvortex/core/RoundStatusTest.scala
  core-test/src/test/scala/com/lnvortex/core/UTXOWarningTest.scala
  core/src/main/scala/com/lnvortex/core/RoundDetails.scala
  core/src/main/scala/com/lnvortex/core/RoundStatus.scala
  core/src/main/scala/com/lnvortex/core/UTXOWarning.scala
  testkit/src/main/scala/com/lnvortex/testkit/VortexClientManagerFixture.scala
Labels: tests

#338 Small clean ups in PeerValidation
  core/src/main/resources/reference.conf
  project/Deps.scala
  server-test/src/test/scala/com/lnvortex/server/coordinator/VortexCoordinatorTest.scala
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
Labels: refactor, coordinator

#339 Fix lnd labeling to overwrite its 'external' label
  client-server-test/src/test/scala/com/lnvortex/server/OnChainTest.scala
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
Labels: bug, lnd

#340 Add static test vectors for message serialization
  core-test/core-test.sbt
  core-test/src/main/scala/com/lnvortex/core/gen/Generators.scala
  core-test/src/main/scala/com/lnvortex/core/gen/VortexMessageTestVectorGen.scala
  core-test/src/test/resources/vortex_messages.json
  core-test/src/test/scala/com/lnvortex/core/VortexMessageSerializationTest.scala
  core/src/main/scala/com/lnvortex/core/VortexMessage.scala
Labels: core, tests

#343 Recover when the transaction does not exist
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
Labels: bug, coordinator

#344 Publish binaries
  .github/workflows/release.yml
  app/rpc-server/rpc-server.sbt
  coordinator/rpc-server/coordinator-rpc-server.sbt
Labels: build, CI

#345 Add coordinator callbacks
  client-server-test/src/test/scala/com/lnvortex/server/ClientServerPairTest.scala
  client-server-test/src/test/scala/com/lnvortex/server/DualClientTest.scala
  server/src/main/scala/com/lnvortex/server/config/CoordinatorCallbacks.scala
  server/src/main/scala/com/lnvortex/server/config/VortexCoordinatorAppConfig.scala
  server/src/main/scala/com/lnvortex/server/coordinator/VortexCoordinator.scala
Labels: enhancement, coordinator

#346 Add twitter and telegram integrations
  build.sbt
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcAppConfig.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/Daemon.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/TelegramHandler.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/TwitterHandler.scala
  core/src/main/scala/com/lnvortex/core/VortexUtils.scala
  develop/src/main/scala/com/lnvortex/develop/CreateLocalDevEnvironment.scala
  project/Deps.scala
Labels: enhancement, coordinator

#347 Try encoding numeric chan id as string
  app/config/src/main/scala/com/lnvortex/config/VortexPicklers.scala
Labels: bug, client

#348 Switch to code cov
  .github/workflows/coverage_report.yml
  .github/workflows/main.yml
Labels: CI

#350 Move website into ln-vortex repo
  .github/workflows/release.yml
  website/.gitignore
  website/README.md
  website/babel.config.js
  website/blog/intro.md
  website/docs/ProtocolDocumentation.md
  website/docs/RpcDocs.md
  website/docs/detailed-protocol.jpeg
  website/docs/intro.md
  website/docs/vortex-dark-mode.svg
  website/docusaurus.config.js
  website/package.json
  website/sidebars.js
  website/src/css/custom.css
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/src/pages/markdown-page.md
  website/static/.nojekyll
  website/static/img/favicon.ico
  website/static/img/logo.svg
Labels: documentation

#351 Fix image in intro docs.
  website/docs/intro.md
  website/static/img/vortex-dark-mode.svg
  website/static/img/vortex-light-mode.svg
Labels: documentation

#356 Start of website homepage
  website/docs/Backends/bitcoind.md
  website/docs/Backends/cln.md
  website/docs/Backends/lnd.md
  website/docs/RpcDocs.md
  website/docusaurus.config.js
  website/package.json
  website/src/pages/index.js
  website/src/pages/index.module.css
  website/static/img/bitcoin.svg
  website/static/img/cln.png
  website/static/img/lnd.png
  website/yarn.lock
Labels: documentation

#357 Lnd docs
  website/docs/Backends/lnd.md
Labels: documentation, lnd

#358 Fix homepage metadata
  website/src/pages/index.js
Labels: documentation

#359 Enable bitcoind backend support
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LightningImplementation.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexAppConfig.scala
  build.sbt
  core/src/main/resources/reference.conf
Labels: bitcoind

#360 Add CLN and bitcoind docs
  website/docs/Backends/bitcoind.md
  website/docs/Backends/cln.md
  website/docs/Backends/lnd.md
Labels: documentation

#361 Add taproot enabled section to website
  website/src/css/custom.css
  website/src/pages/index.js
  website/static/img/carrot-tornado.png
Labels: documentation

#362 Update website deps
  website/package.json
  website/yarn.lock
Labels: documentation, dependencies

#364 Always test vortexMessageWrites
  core-test/src/test/scala/com/lnvortex/core/VortexMessageSerializationTest.scala
Labels: tests
