Repository ln-vortex/ln-vortex, pull requests merged in 2022-10, with the labels that each got.

#366 Add quick start guide
  website/docs/Backends/index.md
  website/docs/ProtocolDocumentation.md
  website/docs/RpcDocs.md
  website/docs/configuration.md
  website/docs/intro.md
  website/docs/quick-start.md
  website/docs/verifying-binaries.md
  website/docusaurus.config.js
Labels: documentation

#370 Update deps
  project/Deps.scala
Labels: dependencies

#373 Update sbt to v1.7.2
  project/build.properties
Labels: build

#374 Update some deps
  project/Deps.scala
Labels: dependencies

#375 Change to PlayJson in RpcServer
  app/rpc-server/src/main/scala/com/lnvortex/rpc/RpcServer.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/ServerCommand.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/ServerJsonModels.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/VortexClientRpcRoutes.scala
  app/rpc-server/src/main/scala/de/heikoseeberger/akkahttpupickle/UpickleSupport.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcServer.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/ServerCommand.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/VortexCoordinatorRpcRoutes.scala
  coordinator/rpc-server/src/main/scala/de/heikoseeberger/akkahttpupickle/UpickleSupport.scala
  project/Deps.scala
Labels: dependencies

#372 Add CORS handling
  app/rpc-server/src/main/scala/com/lnvortex/rpc/CORSHandler.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/RpcServer.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CORSHandler.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcServer.scala
Labels: enhancement

#376 Fix cors handling for coordinator rpc
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcServer.scala
Labels: bug

#378 Add Voltage docs
  website/docs/ProtocolDocumentation.md
  website/docs/voltage.md
Labels: documentation

#391 Move min lnd to v0.15.2
  README.md
  build.sbt
  lnd/src/main/scala/com/lnvortex/lnd/LndVortexWallet.scala
  testkit/src/main/scala/com/lnvortex/testkit/LndTestUtils.scala
  website/docs/Backends/lnd.md
Labels: lnd

#393 Allow running release CI on dispatch
  .github/workflows/release.yml
Labels: CI

#396 Upgrade bitcoin-s to 1.9.6
  project/Deps.scala
Labels: dependencies

#403 Verify that coinbase inputs have correct confirmations
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
Labels: bug, coordinator

#405 Automatically start tor if configured
  app/rpc-server/src/main/scala/com/lnvortex/rpc/Daemon.scala
  core/src/main/resources/reference.conf
Labels: client

#409 Add test for conflicting tx in mempool
  server-test/src/test/scala/com/lnvortex/server/coordinator/VortexCoordinatorTest.scala
  server/src/main/scala/com/lnvortex/server/internal/PeerValidation.scala
Labels: coordinator, tests

#411 Add telegram and twitter options to docker config
  coordinator/rpc-server/src/universal/docker-application.conf
Labels: coordinator

#410 Update bitcoin-s and binary downloaders
  README.md
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexAppConfig.scala
  build.sbt
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcAppConfig.scala
  project/Deps.scala
  testkit/src/main/scala/com/lnvortex/testkit/CLNTestUtils.scala
  testkit/src/main/scala/com/lnvortex/testkit/LndTestUtils.scala
  testkit/src/main/scala/com/lnvortex/testkit/LndVortexWalletFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/VortexClientFixture.scala
  testkit/src/main/scala/com/lnvortex/testkit/VortexClientManagerFixture.scala
  website/docs/Backends/lnd.md
Labels: dependencies

#413 Put default rpc cookie in main directory
  app/config/src/main/scala/com/lnvortex/config/LnVortexRpcServerConfig.scala
Labels: documentation

#414 Update bitcoin-s
  app/config/src/main/scala/com/lnvortex/config/LnVortexRpcServerConfig.scala
  app/rpc-server/src/main/scala/com/lnvortex/rpc/LnVortexAppConfig.scala
  coordinator/rpc-server/src/main/scala/com/lnvortex/coordinator/rpc/CoordinatorRpcAppConfig.scala
  project/Deps.scala
Labels: dependencies

#418 Update homepage
  project/CommonSettings.scala
Labels: build
